apiVersion: v1
kind: PersistentVolume
metadata:
  name: sa-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/code/sa